### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by samuelrkramer**
Added in a Notable Features section at the top of the readme.

As an aside, I think we should keep this branch after merging into main and periodically edit it when needed, and even branch from it if we have to spend some time tinkering it.

### CODE REVIEW

**Comment by samuelrkramer** [comment]
> As an aside, I think we should keep this branch after merging into main and periodically edit it when needed, and even branch from it if we have to spend some time tinkering it.

Also I think this would look super-cool in that network graph. But I recognize that's not a reason to do something

**Review by jonevanmoore — APPROVED** [review]
Nice!

**Review by Nick-Yawn — APPROVED** [review]
Looks great!

**Review by MasonKogami — APPROVED** [review]
Lookin' good!

**Pull request merged**
