### PR TITLE
profile info done

### PR DESCRIPTION
**Pull request by jonevanmoore**
Took longer than I should have on this, but it's done
Image 3-18-22 at 4 13 PM

### CODE REVIEW

**Review by MasonKogami — APPROVED** [review]

**Comment by Nick-Yawn** [comment]
Wow, that's cool! Also, spooky!

**Review by Nick-Yawn — APPROVED** [review]

**Comment by Nick-Yawn** [comment]
oh, but it may help to merge main into this, resolve the conflicts, then commit again

**Review by Nick-Yawn — CHANGES_REQUESTED** [review]
Looking at the network graph, this branch has not been caught up with main lately, so main should be pulled and merged into this before it is merged back.

**Review by Nick-Yawn — APPROVED** [review]
Looks good!

**Review by samuelrkramer — COMMENTED** [review]
Really cool, and the random images caught me hilariously off-guard

**Pull request merged**
